import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { ChakraProvider } from '@/components/provider/ChakraProvider'

const poppins = Poppins({ subsets:["latin-ext"],weight:["400","500", "600", "700"] })

export const metadata: Metadata = {
  title: 'Welcome bitch',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ChakraProvider>
          {children}
        </ChakraProvider>
      </body>
    </html>
  )
}
